"""empty message

Revision ID: 5cbcc87798ef
Revises: a3e48add472c
Create Date: 2022-11-07 11:42:19.577623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cbcc87798ef'
down_revision = 'a3e48add472c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_added', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_added')
    # ### end Alembic commands ###
