"""empty message

Revision ID: a3e48add472c
Revises: 6b4c09d1bc8a
Create Date: 2022-11-07 11:14:39.807484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e48add472c'
down_revision = '6b4c09d1bc8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
